hazelcast-client:
  # Name of the cluster to connect to. Must match the name configured on the
  # cluster members.
  cluster-name: jet
#  user-code-deployment:
#    enabled: true
#    jarPaths:
#      - order-payment-job-1.0-SNAPSHOT.jar
#    classNames:
#      - org.example.state.OrderState
#      - org.example.state.OrderState.OrderStateSerializer
#      - org.example.state.PaymentState
#      - org.example.state.PaymentState.PaymentStateSerializer
  network:
    # List of addresses for the client to try to connect to. All members of
    # a Hazelcast Jet cluster accept client connections.
    # Use the format <hostname>:<port>
    # If a port number is not specified, port range 5701-5703 will be tried.
    cluster-members:
      - 127.0.0.1
    # Whether client should discover and connect other members in the cluster
    # and route requests to them or only connects to the members listed
    # above.
    smart-routing: false
    join:
      # The default way to discover nodes: using the IP multicast. This is the
      # simplest technique, but in a cloud setting the network usually doesn't
      # allow multicast.
      multicast:
        enabled: false
        multicast-group: 224.2.2.3
        multicast-port: 54328
      # This technique doesn't attempt any auto-discovery, you directly list all
      # the candidate IPs to check.
      tcp-ip:
        enabled: true
        member-list:
          - 192.168.1.21
          - 192.168.1.22
          - 192.168.1.23
  connection-strategy:
    connection-retry:
      # how long the client should keep trying connecting to the server
      cluster-connect-timeout-millis: 1000
